default_label = "9mm Black on SteelBlue"
default_canvas_width = 200
load_system_fonts = true
font_favourites = [
    "Helvetica",
    "Times",
    "Terminus",
    "Spleen",
    "ProFontOTB",
    "Thermal Sans Mono",
    "Tiny5",
]
